version: "3.6"

services:
  go:
    image: golang:1.17
    tty: true
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - ./:/app:Z
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - backend

  postgres:
    image: postgres:14.1
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
